$(document).ready(function(){
  $("#start").click(function(event){
    event.preventDefault();
    $("#playerone").show();
  });
  $("#startTwo").click(function(event){
    event.preventDefault();
    $("#playerTwo").show();
  });
});
